# Generated by Django 4.1 on 2022-08-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='query',
            field=models.CharField(max_length=200),
        ),
    ]
